// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9I2S9r1k8XyOL04Hznk9wg1NQz4PCIbE',
    appId: '1:776326341244:web:e31c204b1d185f74271ff9',
    messagingSenderId: '776326341244',
    projectId: 'mintmate-9c857',
    authDomain: 'mintmate-9c857.firebaseapp.com',
    storageBucket: 'mintmate-9c857.firebasestorage.app',
    measurementId: 'G-P56RBZRZYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDycQfTwfS0TQWhWLv7q_QLvi_CWay6Loc',
    appId: '1:776326341244:android:8c7c2e84b40c0227271ff9',
    messagingSenderId: '776326341244',
    projectId: 'mintmate-9c857',
    storageBucket: 'mintmate-9c857.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfbvcpqUFNAeT9tJM45z5do0bfFrlnguU',
    appId: '1:776326341244:ios:d289c64821b499f4271ff9',
    messagingSenderId: '776326341244',
    projectId: 'mintmate-9c857',
    storageBucket: 'mintmate-9c857.firebasestorage.app',
    iosBundleId: 'com.example.mintmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfbvcpqUFNAeT9tJM45z5do0bfFrlnguU',
    appId: '1:776326341244:ios:d289c64821b499f4271ff9',
    messagingSenderId: '776326341244',
    projectId: 'mintmate-9c857',
    storageBucket: 'mintmate-9c857.firebasestorage.app',
    iosBundleId: 'com.example.mintmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9I2S9r1k8XyOL04Hznk9wg1NQz4PCIbE',
    appId: '1:776326341244:web:9a1eb276db368e3a271ff9',
    messagingSenderId: '776326341244',
    projectId: 'mintmate-9c857',
    authDomain: 'mintmate-9c857.firebaseapp.com',
    storageBucket: 'mintmate-9c857.firebasestorage.app',
    measurementId: 'G-LVWKZJP3DY',
  );
}
